# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rnlogin' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rnlogin
  pod 'AFNetworking', '~> 3.0'
  pod 'KVNProgress', '~> 2.2.4'
  pod 'SSZipArchive'
  pod 'Reachability', '~> 3.2'
end
